version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chatapp
hooks:
  BeforeInstall:
      timeout: 300
  AfterInstall:
      timeout: 300
  ApplicationStart:
    - location: script/start-server.sh
      timeout: 300
      runas: root
