version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chatapp
hooks:
  BeforeInstall:
      timeout: 500
      runas: root
ApplicationStart:
    - location: script/start-server.sh
      timeout: 800
      runas: root
